stages:
    - build
    - test

build:
    stage: build
    image: node:14.18.3
    script:
        - npm install
        - export CI=false
        - npm run build
    artifacts:
        paths:
            - "build/*"

test:
    stage: test
    artifacts:
        paths:
            - file.txt
    image: "docker:20.10.12"
    dependencies:
        - build
    script:
        - ls | tee file.txt

deploy:
    image: "docker:20.10.12"
    dependencies:
        - build
    script:
        - cp build/* server/Site/
        - docker build -it parker-website
        - docker rm parker-website
        - docker run -it -d -p 8181:80 --name parker-website parker-website