stages:
    - build
    - deploy

build:
    stage: build
    image: node:14.18.3
    script:
        - npm install
        - export CI=false
        - npm run build
    artifacts:
        paths:
            - "build/*"

deploy:
    stage: deploy
    image: "docker:20.10.12"
    dependencies:
        - build
    allow_failure: true
    script:
        - ls server
        - cp -R build/* ./server/Site
        - docker build -t parker-website .
        - "docker stop parker-website || true && docker rm parker-website || true"
        - docker run -it -d -p 8181:80 --restart=unless-stopped
 --name parker-website parker-website